name: Run tests
on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Download LLVM, botan
        run: sudo apt-get install llvm-14 clang libbotan-2-dev botan
      - name: Download Odin
        run: |
          git clone https://github.com/odin-lang/Odin
          cd Odin
          ./build_odin.sh release
      - name: Run tests
        run: ./odin run ../tests
